// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace BDefenderAppML.Model
{
    public class ModelInput
    {
        [ColumnName("col0"), LoadColumn(0)]
        public float Col0 { get; set; }


        [ColumnName("col1"), LoadColumn(1)]
        public string Col1 { get; set; }


        [ColumnName("col2"), LoadColumn(2)]
        public float Col2 { get; set; }


        [ColumnName("col3"), LoadColumn(3)]
        public float Col3 { get; set; }


        [ColumnName("col4"), LoadColumn(4)]
        public float Col4 { get; set; }


        [ColumnName("col5"), LoadColumn(5)]
        public float Col5 { get; set; }


        [ColumnName("col6"), LoadColumn(6)]
        public float Col6 { get; set; }


        [ColumnName("col7"), LoadColumn(7)]
        public float Col7 { get; set; }


        [ColumnName("col8"), LoadColumn(8)]
        public float Col8 { get; set; }


        [ColumnName("col9"), LoadColumn(9)]
        public float Col9 { get; set; }


        [ColumnName("col10"), LoadColumn(10)]
        public float Col10 { get; set; }


        [ColumnName("col11"), LoadColumn(11)]
        public float Col11 { get; set; }


        [ColumnName("col12"), LoadColumn(12)]
        public float Col12 { get; set; }


        [ColumnName("col13"), LoadColumn(13)]
        public float Col13 { get; set; }


        [ColumnName("col14"), LoadColumn(14)]
        public float Col14 { get; set; }


        [ColumnName("col15"), LoadColumn(15)]
        public float Col15 { get; set; }


        [ColumnName("col16"), LoadColumn(16)]
        public float Col16 { get; set; }


        [ColumnName("col17"), LoadColumn(17)]
        public float Col17 { get; set; }


        [ColumnName("col18"), LoadColumn(18)]
        public float Col18 { get; set; }


        [ColumnName("col19"), LoadColumn(19)]
        public float Col19 { get; set; }


        [ColumnName("col20"), LoadColumn(20)]
        public float Col20 { get; set; }


        [ColumnName("col21"), LoadColumn(21)]
        public float Col21 { get; set; }


        [ColumnName("col22"), LoadColumn(22)]
        public float Col22 { get; set; }


        [ColumnName("col23"), LoadColumn(23)]
        public float Col23 { get; set; }


        [ColumnName("col24"), LoadColumn(24)]
        public float Col24 { get; set; }


        [ColumnName("col25"), LoadColumn(25)]
        public float Col25 { get; set; }


        [ColumnName("col26"), LoadColumn(26)]
        public float Col26 { get; set; }


        [ColumnName("col27"), LoadColumn(27)]
        public float Col27 { get; set; }


        [ColumnName("col28"), LoadColumn(28)]
        public float Col28 { get; set; }


        [ColumnName("col29"), LoadColumn(29)]
        public float Col29 { get; set; }


        [ColumnName("col30"), LoadColumn(30)]
        public float Col30 { get; set; }


        [ColumnName("col31"), LoadColumn(31)]
        public float Col31 { get; set; }


    }
}
